# Generated by Django 2.2.6 on 2020-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200530_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='book',
            field=models.ManyToManyField(to='p_library.Book'),
        ),
    ]
