# Generated by Django 2.2.6 on 2020-05-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
        migrations.CreateModel(
            name='PublisherBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb_book', to='p_library.Book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pb_publisher', to='p_library.Publisher')),
            ],
        ),
    ]
